### ISSUE TITLE
Response code override on fmgr_pm_pkg module not working

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#92] opened 2024-11-20 08:04 UTC
Hi!

I've updated our collection to the latest version and since then I'm unable to override response codes for succeeded. I have a task that deletes the `default` policy, but if the automation needs to be ran twice for some reason and the `default` policy has been removed already then the task fails with code `-6` (_Invalid url_). What I did previously was override the `rc_succeeded` with `-6` so it wouldn't fail if the package did not exist. Since the new version I'm unable to do so as the task will still fail even when it says that succeeded is already overridden with `-6`.

Task:
```
# Delete default policy package from adom. Task is only ran if a new ADOM is created
- name: Delete default policy package from {{ adom_name | lower }}
  fortinet.fortimanager.fmgr_pm_pkg:
    workspace_locking_adom: "{{ adom_name | lower }}"
    adom: "{{ adom_name | lower }}"
    state: absent
    pkg_path: "default/"
    pm_pkg:
      name: "default"
      type: "pkg"
    rc_succeeded:
      - -6
```

Response:
```
fatal: [fortimanager01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "adom": "raittest1",
            "bypass_validation": false,
            "enable_log": false,
            "forticloud_access_token": null,
            "pkg_path": "default/",
            "pm_pkg": {
                "name": "default",
                "obj ver": null,
                "oid": null,
                "package setting": null,
                "package settings": null,
                "scope member": null,
                "type": "pkg"
            },
            "proposed_method": null,
            "rc_failed": null,
            "rc_succeeded": [
                -6
            ],
            "state": "absent",
            "workspace_locking_adom": "testadom",
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/pm/pkg/adom/testadom/default/",
        "response_code": -6,
        "response_data": [],
        "response_message": "Invalid url",
        "result_code_overriding": "rc code:-6 is overridden to success",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "2553",
            "Build": "2553",
            "Current Time": "Wed Nov 20 09:59:49 EET 2024",
            "Daylight Time Saving": "Yes",
            "FIPS Mode": "Disabled",
            "HA Mode": "Stand Alone",
            "Hostname": "FMG",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 2,
            "Max Number of Device Groups": 3,
            "Minor": 4,
            "Offline Mode": "Disabled",
            "Patch": 5,
            "Platform Full Name": "FortiManager-VM64-HV",
            "Platform Type": "FMG-VM64-HV",
            "Release Version Information": " (GA.M)",
            "Serial Number": "FMG-",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.4.5-build2553 241016 (GA.M)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": -6
}
```

**Comment by dux-fortinet** [comment] 2024-11-20 19:05
Hi @cr0cdev,

Thanks for pointing it out and I apologize for this BUG.
I have found the cause, and am working on a quick patch. FortiManager Ansible 2.8.1 will be released this Friday (Nov 20).

Regards,
Dux

**Comment by dux-fortinet** [comment] 2024-11-22 20:05
Hi @cr0cdev,

FortiManager Ansible 2.8.1 has been released and this BUG has been fixed.

Best regards,
Dux

**Closed** 2024-11-27 19:55 UTC
